[project]
name = "republic-prompt"
version = "0.4.0"
description = "Modern prompt engineering workspace library with clean architecture"
authors = [
    {name = "Psiace", email = "psiace@apache.org"}
]
readme = "README.md"
license = {text = "Apache-2.0"}
requires-python = ">=3.11"
keywords = ["prompt", "template", "ai", "llm", "jinja2", "workspace"]

dependencies = [
    "jinja2 >= 3.1.0",
    "pydantic >= 2.0.0",
    "pydantic-settings >= 2.0.0",
    "tomli >= 2.0.0",
    "pyyaml>=6.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest >= 7.0.0",
    "ruff >= 0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/republic_prompt"]
