[project]
name = "republic-prompt"
version = "0.1.0"
description = "Manage your prompts as recipes."
readme = "README.md"
authors = [
    { name = "Chojan Shang", email = "psiace@apache.org" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/republic_prompt"]